### PR TITLE
Update link to Jupyter logo

### LINKED ISSUE #328: Broken link to Jupyter graphic
Our link-checker has been failing for a while now, e.g. https://github.com/ProjectPythia/pythia-foundations/actions/runs/3223393187

The culprit is a graphic at the top of the [Getting Started with Jupyter](https://foundations.projectpythia.org/foundations/getting-started-jupyter.html) page, which links to https://datascience.foundation/backend/web/uploads/blog/Working-with-Python-on-Cloud.png. Seems the datascience.foundation link is inactive.

I don't remember what this graphic actually was. Should we just replace it with a [Jupyter logo](https://jupyter.org/assets/homepage/main-logo.svg)?

### PR DESCRIPTION
**Pull request by ktyle**
Fixes #328. Note that the new SVG logo is quite a bit smaller than the PNG that we linked to before, but IMHO it's ok.

### CODE REVIEW

**Comment by brian-rose** [comment]
> Fixes #328. Note that the new SVG logo is quite a bit smaller than the PNG that we linked to before, but IMHO it's ok.

I tried setting `width=400` in the image tag so it's consistent with the logos we're using in the GitHub section.

**Comment by brian-rose** [comment]
I mangled something, sorry. Will fix now.

**Comment by dopplershift** [comment]
If we wanted the same rectangle, it's available on GitHub at: https://github.com/jupyter/jupyter.github.io/blob/master/assets/logos/rectanglelogo-greytext-orangebody-greymoons.svg

**Review by brian-rose — APPROVED** [review]

**Comment by brian-rose** [comment]
Can we please get another review here so we can merge this and finally fix the link checker failure?

Tagging a few likely folks...
@jukent @dcamron @r-ford

**Review by r-ford — APPROVED** [review]

**Pull request merged**
