### PR TITLE
Add new matplotlib notebook

### PR DESCRIPTION
**Pull request by mgrover1**
Another section of matplotlib content, originally put together by @anissa111, with some additional narration/theme matching.

Towards #167

### CODE REVIEW

**Comment by mgrover1** [comment]
@michaelavs could you take a look at this soon?

**Comment by brian-rose** [comment]
Hi @mgrover1 , I added a bunch of comments on reviewnb. 

I'm glad I read through this because I learned about `subplot_mosaic` for the first time! That's a feature I've been waiting for.

**Comment by michaelavs** [comment]
Hi @mgrover, 
Sorry for any delays caused by me, I didn't realize I was listed as a reviewer on this PR! 

I went through on reviewnb and added a couple comments, but I think things look good overall!

**Comment by brian-rose** [comment]
@mgrover1 I can't find my comments anywhere, nor those from @michaelavs. Seems that ReviewNB may have eaten them for breakfast. I will just start over and do a new review.

**Comment by brian-rose** [comment]
> @mgrover1 I can't find my comments anywhere, nor those from @michaelavs. Seems that ReviewNB may have eaten them for breakfast. I will just start over and do a new review.

Actually now I CAN see our comments at https://app.reviewnb.com/ProjectPythia/pythia-foundations/blob/advanced_matplotlib/core/matplotlib/additional-topics2.ipynb/
I'm not sure what's going on, or why the comments never migrated over to this GitHub discussion.

**Comment by jukent** [comment]
I'm gonna see what I can do to get this content merge-able

**Pull request closed without merging**
