### PR TITLE
Polish Matplotlib content for consistency

### PR DESCRIPTION
**Pull request by brian-rose**
This PR goes through all the Matplotlib content and makes a number of small tweaks for style and consistency, including
- Rationalizing the titles and notebook file names
- Consistent capitalization of the words "Matplotlib" and "Python" in the text
- Adding the notebook output file `animate.gif` to the git ignore list
- Tweaks to various links
- Making the Matplotlib logo appear the same on each page

### CODE REVIEW

**Comment by brian-rose** [comment]
Closes #234

**Comment by jukent** [comment]
@brian-rose Thanks for doing this! I just saw one irregularity on the `matplotlib.md` page that says we've taught 3D plotting. For some reason I'm unable to suggest an edit to that line.

**Comment by brian-rose** [comment]
> @brian-rose Thanks for doing this! I just saw one irregularity on the `matplotlib.md` page that says we've taught 3D plotting. For some reason I'm unable to suggest an edit to that line.

Thanks, good catch, I'll fix that now.

**Review by jukent — APPROVED** [review]
Great job!

**Review by r-ford — APPROVED** [review]
Looks good!

**Pull request merged**
