### PR TITLE
Make the book title consistently "Pythia Foundations"

### LINKED ISSUE #176: Book title: "Pythia Foundations" or "Project Pythia Foundations"?
In preparing a video supplement for the Foundations book (#127), @ncorbin-id has identified an ambiguity in the title of the book.

The [landing page](https://foundations.projectpythia.org/landing-page.html) and TOC reference "Project Pythia Foundations".
But the [Preamble](https://foundations.projectpythia.org/preamble/how-to-use.html) (and possibly elsewhere) repeatedly references "Pythia Foundations".

I think we should choose a title and stay consistent! 

FWIW, my vote would be "Pythia Foundations" as the book title.

### PR DESCRIPTION
**Pull request by brian-rose**
Partially addresses #176.

The book title will need to be fixed on the Portal as well.

### CODE REVIEW

**Comment by jukent** [comment]
Is there a need to pin 'mamba' still?

**Comment by brian-rose** [comment]
> Looks great! Just wondering if there is still a need to repin 'mamba'?

Argh, no, sorry! That crept in due to a merge conflict I think. I will fix.

**Review by r-ford — APPROVED** [review]
In the "How to Use This Book" section, there are two cases of "Foundation" needing an "s". Other than that, looks good.

**Comment by brian-rose** [comment]
> In the "How to Use This Book" section, there are two cases of "Foundation" needing an "s". Other than that, looks good.

Thanks for spotting that! I fixed those typos and will merge this.

**Pull request merged**
