### PR TITLE
Revert PR#123 changes in favor of pydata-sphinx-theme v0.7.0 

### LINKED ISSUE #128: Revert Google Analytics Workaround Once pydata_sphinx_theme Fix Released
We now have Google Analytics working for our Foundations Book with the help of PR #123. 

Our PR was just a workaround until [pydata/pydata-sphinx-theme#439](https://github.com/pydata/pydata-sphinx-theme/pull/439)gets merged and released. So, once it is done, our PR #123 should better be reverted.

### PR DESCRIPTION
**Pull request by erogluorhan**
Closes #128 by reverting the changes of PR #123.

pydata-sphinx-theme released v0.7.0 that fixes their Google Analytics handling.

### CODE REVIEW

**Comment by brian-rose** [comment]
So maybe we just need to let this simmer until things get updated upstream.

**Comment by erogluorhan** [comment]
Opened [Issue#18](https://github.com/conda-forge/sphinx-book-theme-feedstock/issues/18) at sphinx-book-theme-feedstock for this.

**Comment by andersy005** [comment]
Now that there's a new version of `sphinx-book-theme`, it might a good time to revisit this

**Comment by erogluorhan** [comment]
> Now that there's a new version of `sphinx-book-theme`, it might a good time to revisit this

Yes, I will, thanks!

**Comment by kmpaul** [comment]
Yes.  With the newest release, the Jupyter Book config option for GA should work, even with newer `G-???` tags.

**Review by kmpaul — APPROVED** [review]
Great!  Thanks, @erogluorhan!

**Pull request merged**
