### PR TITLE
Remove linting workflow in favor of pre-commit-ci

### PR DESCRIPTION
**Pull request by kmpaul**
According to ProjectPythia/projectpythia.github.io#195, the use of the v2 pre-commit GitHub Action in our `linting.yml` workflow has a security vulnerability.  However, this workflow is redundant with the use of the pre-commit-ci service.  So, I am creating a PR to remove this workflow entirely.

### CODE REVIEW

**Comment by ktyle** [comment]
@kmpaul This sounds good to me, but I'm not well-versed in things CI. One practical question: in my workflow, after I've made my changes and staged them via `git add`, I then run `pre-commit`; if it finds and fixes anything, I then repeat the `git add`, then run `git commit` and `git push`. Should I continue to follow this workflow?

**Comment by kmpaul** [comment]
@ktyle:  Yes.  You should continue to do that.  This PR really doesn't effect that workflow at all.

We are currently using the **pre-commit.ci** service to run pre-commit on all PRs.  This will run the same pre-commit that you run locally, but on a CI VM.  The result of this is listed as the `pre-commit.ci - pr` check in the PR checks.

We *also* had a separate GitHub workflow that explicitly ran pre-commit for us, using the `pre-commit/action` GitHub action.  This effectively did the same thing as the **pre-commit.ci** service, but it used an old version of the pre-commit action, and was labeled as a security vulnerability.

So, we were actually running pre-commit on the PR *twice*, and one of those runs had a security vulnerability.  So, I just deleted the one with the security vulnerability.

**Review by dopplershift — APPROVED** [review]

**Review by ktyle — APPROVED** [review]
Thanks for the explanation, @kmpaul !

**Comment by kmpaul** [comment]
Thanks @ktyle  and @dopplershift!  Merged!

**Pull request merged**
