### PR TITLE
Fix broken link about lunar day, and remove dead link to NASA dataset interoperability

### LINKED ISSUE #494: Broken link causing nightly build failure
E.g. [this build log](https://github.com/ProjectPythia/pythia-foundations/actions/runs/11471447575/job/31922358038#step:7:195)

Nightly build should pass again, finally, if we replace this dead link in the [Times and Dates notebook](https://foundations.projectpythia.org/core/datetime/datetime.html#calculating-coastal-tides-with-the-timedelta-class).

The link is about the definition of lunar day. The old link to http://oceanservice.noaa.gov/education/kits/tides/media/supp_tide05.html seems to be dead. I'll look through the NOAA educational site to find something equivalent.

### PR DESCRIPTION
**Pull request by brian-rose**
Closes #494

### CODE REVIEW

**Comment by brian-rose** [comment]
There's another broken link now... will try to fix.

**Comment by brian-rose** [comment]
I removed a link in the final "References" section of the NetCDF notebook. The link was to something related to NASA dataset interoperability recommendations for earth science. I'm not sure exactly what was linked. A google search on this topic yielded a number of different technical documents, but it wasn't clear to me that there was a lot of value in promoting these as recommended follow-up reading for our chapter.

**Comment by dopplershift** [comment]
Looks like [this](https://wiki.earthdata.nasa.gov/display/ESDSWG/Dataset+Interoperability+Recommendations+for+Earth+Science) contains the recommendations extracted from the original. Not sure if it's worth linking.

**Comment by brian-rose** [comment]
> Not sure if it's worth linking.

In my opinion, no. It's a technical report from a technical working group, not a tutorial document.

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
