### PR TITLE
Cartopy links

### LINKED ISSUE #144: Broken links in `core/cartopy/cartopy`
Link-checker is failing PR #131 due to broken links in `core/cartopy` - which was not changed in this PR. So we have some broken links upstream?

```
(    core/cartopy: line   16) broken    https://scitools.org.uk/cartopy/docs/latest/crs/projections.html#cartopy-projections - 404 Client Error: Not Found for url: https://scitools.org.uk/cartopy/docs/latest/crs/projections.html
(core/cartopy/cartopy: line 650005) broken    https://scitools.org.uk/cartopy/docs/latest/crs/projections.html - 404 Client Error: Not Found for url: https://scitools.org.uk/cartopy/docs/latest/crs/projections.html
```

### PR DESCRIPTION
**Pull request by jukent**
Closes #144

### CODE REVIEW

**Comment by jukent** [comment]
Same book failure as the other PRs.

**Comment by jukent** [comment]
Changed links to: https://scitools.org.uk/cartopy/docs/latest/reference/crs.html#list-of-projections at @dopplershift 's suggestion

**Review by mgrover1 — APPROVED** [review]
Thanks for making these changes @jukent

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Ignoring the deploy failure (#146).

**Pull request merged**
