### PR TITLE
Remove Linkify from _config.yaml

### LINKED ISSUE #130: Linkify too aggressive
In my most recent PR #129 JupyterBook kept trying to render a file path as an html link. I think this is because we have linkify set up to automatically detect links, and it is too aggressive. I'm not sure if we want to disable linkify or perhaps find a way to tone it down.

https://github.com/ProjectPythia/pythia-foundations/blob/000661ff92f544e95efdaebe88c2c10b1f3c734b/_config.yml#L28

### PR DESCRIPTION
**Pull request by jukent**
Per discussion on and closes #130

### CODE REVIEW

**Comment by jukent** [comment]
Well the book deploy is failing now with just one small change, so maybe `linkify` is being used in ways beyond what we originally thought. I don't have time to look into this right now.

**Comment by andersy005** [comment]
> Well the book deploy is failing now with just one small change,

This has to do with a permission issue. I'll look into it later today

Screen Shot 2021-09-16 at 1 35 43 PM

**Comment by brian-rose** [comment]
Seems like a weird failure to me. I will try a quick "close and reopen" and see if we get the same result.

**Comment by brian-rose** [comment]
@jukent @andersy005 I verified over at #141 that we get the same failure for a trivial PR that doesn't touch `linkify` or anything in the configurations.

**Comment by andersy005** [comment]
> > Well the book deploy is failing now with just one small change,
> 
> This has to do with a permission issue. I'll look into it later today
> 
> Screen Shot 2021-09-16 at 1 35 43 PM


This should be fixed ...

**Review by erogluorhan — APPROVED** [review]
This looks good to me based on the consensus after the discussions.

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
