### PR TITLE
Reording Navbar links to prioritize Pythia produced content

### PR DESCRIPTION
**Pull request by jukent**
Putting Cookbooks before Resources. This is also done on the Portal in https://github.com/ProjectPythia/projectpythia.github.io/pull/256 and will be need to be done in the Cookbooks template and each cookbook as well.

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]
Great, thanks @jukent!

I wonder if there's some clever automation we might use to keep the navbar in sync between all the different sites and repos. If not, we should try to make sure we're happy with it before we start building lots of Cookbooks. We can discuss this at the EWG this week.

**Comment by jukent** [comment]
@brian-rose I've added this to the agenda. I think we should wait to merge this until we merge https://github.com/ProjectPythia/projectpythia.github.io/pull/256 to keep the sites consistent.

**Comment by brian-rose** [comment]
@jukent is it time to revisit / merge this one now?

**Comment by brian-rose** [comment]
Actually it seems like the navbar has already been updated on the foundations site... I must have missed something.

**Comment by jukent** [comment]
> Actually it seems like the navbar has already been updated on the foundations site... I must have missed something.

I forgot about this PR and did it in #294 I'm surprised there aren't merge conflicts now. I'm going to close this.

**Pull request closed without merging**
