### PR TITLE
First pass at dask

### PR DESCRIPTION
**Pull request by mgrover1**
Addresses #108 - again, not sure if this falls completely within this foundations book, but I would consider it to be fairly foundational. Other sections we could add would be numba? Basically including how to "level up" your code to be scalable. Thoughts + comments are appreciated.

### CODE REVIEW

**Comment by brian-rose** [comment]
Just checking in @mgrover1, I'm tagged for a review here. Would it be more useful for me to do a full review now, or wait until after you've had a chance to incorporate some of the existing suggestions?

**Comment by mgrover1** [comment]
I will make those changes first - sorry for the delay

**Comment by brian-rose** [comment]
> I will make those changes first - sorry for the delay

No worries whatsoever. Just wanted to make sure my lack of review wasn't holding this up.

**Comment by mgrover1** [comment]
Closing now that we have a dask-cookbook!

**Pull request closed without merging**
