### PR TITLE
Fix write permission issue that arises during pull_request events

### PR DESCRIPTION
**Pull request by andersy005**
Addresses https://github.com/ProjectPythia/pythia-foundations/pull/139#issuecomment-921190200. 

GitHub restricts permissions granted to the default `GITHUB_TOKEN`:

> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository. The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information, see "Authenticating with the GITHUB_TOKEN."

See the [docs for more](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token). 

To circumvent this restriction, I moved the workflow steps that need `GTIHUB_TOKEN` with write permissions to the `preview-book` workflow which is trigger on `on: workflow_run:`

### CODE REVIEW

**Comment by andersy005** [comment]
To confirm that this is working as expected requires merging this PR. It's for this reason that I am going to merge this as is

**Review by mgrover1 — APPROVED** [review]
Looks good @andersy005 !

**Comment by andersy005** [comment]
Found a bug :)

**Comment by jukent** [comment]
The link checker error will be fixed by #145

**Pull request merged**
