### PR TITLE
Add GHA for book preview via Netlify

### LINKED ISSUE #5: Need an autobuild for pull requests
Before we start opening new PRs to add content to this book, it would be great to get an autobuild triggered for each PR so we can see updates to the rendered book. For the main portal repo, this was accomplished with readthedocs. 

The build is slightly different in this case because it depends on `jupyter-book`. @andersy005 can you advise on how to set this up?

### PR DESCRIPTION
**Pull request by andersy005**
Closes #5

### CODE REVIEW

**Comment by brian-rose** [comment]
Thanks @andersy005, I can see that it's not possible to download a zip file with the built site.

Is the preview visible somewhere without downloading the zip?

**Comment by andersy005** [comment]
> I'm probably missing something, but it the preview visible somewhere without downloading the zip?

You are not missing anything, @brian-rose. This PR is still missing some pieces. I'm still looking into ways to deal with how GitHub shares secrets with pull requests. I will post an updates here once I figure it out.

**Comment by andersy005** [comment]
@brian-rose, this is ready. The solution I came up with consists of a GitHub action that circumvents the GitHub action secrets sharing issue (for pull requests from forks) I previously mentioned. For each successful, the GitHub action will post a comment with a preview link. For instance:

> 🚀 📚 Preview for git commit SHA: [e59fbb4](https://github.com/ProjectPythia/pythia-foundations/commit/e59fbb406121c5ddea5abbd177ffd20b13f8b85a) at: [6030455502ba8952142f232f--pythia-foundations.netlify.app](https://6030455502ba8952142f232f--pythia-foundations.netlify.app)


Let me know if this is enough and/or you have any feature requests :).

**NOTE**: For each git commit/push, the bot will post a new comment. If this is too much, we could add an option to update an existing comment instead.

**Comment by andersy005** [comment]
Also, the workflow that triggers this preview GitHub action is checked into `main` branch already: 

https://github.com/ProjectPythia/pythia-foundations/blob/ad1aa8cf6da741968dee592610a4ff1efdf89bc6/.github/workflows/preview-book.yaml#L29-L45

**Comment by brian-rose** [comment]
@andersy005 this is fantastic! Great work. I think it's ready to merge. We'll try it out as we build out the book contents, and see if any tweaks are needed later.

**Comment by andersy005** [comment]
Awesome! Merging this shortly...

**Pull request merged**
