### PR TITLE
Drop in Unidata pandas workshop notebook

### PR DESCRIPTION
**Pull request by dcamron**
This is a drop-in of [this notebook](https://github.com/Unidata/python-training/blob/master/pages/workshop/Pandas/Pandas%20Introduction.ipynb) from our workshop materials with interactive exercises and Unidata branding removed. Otherwise has so far been unmodified, content-wise.

Notes:
 * Renders pretty well currently. Could (as all of them) use some title reorganization
 * Committed an example csv for reading in
 * Relatively self-sustaining notebook without so much crossover. Scope might be right here, but of course plenty of room for content/style review

### CODE REVIEW

**Comment by jukent** [comment]
Thanks for putting this together @dcamron! Are these recent PRs ready for review?

**Comment by dcamron** [comment]
They are! However I'm in the process right now of putting together all of the current `core` package content (these 6 + @ktyle cartopy) into one rendered book on my fork and opening up a discussion allowing us to view all of them in context and talk about the larger scale picture of those pieces as they sit next to each other. We can also review and merge these individually and then begin that discussion, but our public presentation might be pretty incomplete to anyone that stumbles on it if we don't clearly announce that it's under heavy development (in my opinion).

**Comment by mgrover1** [comment]
Think it would be helpful to add some examples of warnings/

Example of green "success" 
```
<div class="alert alert-block alert-success">
<b>Success:</b> This alert box indicates a successful or positive action.
</div>
```
from https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd

**Comment by dcamron** [comment]
Closing this in favor of #58 (which is based off this).

**Pull request closed without merging**
