### PR TITLE
Added examples to Git commands mini-reference section

### PR DESCRIPTION
**Pull request by anacmontoya**
First draft pull request. Added examples to Basic Version Control with Git > Git commands mini-reference section.

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]
This looks great @anacmontoya! It's a helpful addition.

**Comment by brian-rose** [comment]
This PR is still marked as "Draft". Is it ready to merge @anacmontoya?

**Comment by anacmontoya** [comment]
> This PR is still marked as "Draft". Is it ready to merge @anacmontoya?

it is!

**Comment by brian-rose** [comment]
Thanks for the contribution!

**Pull request merged**
