### PR TITLE
Spinup

### PR DESCRIPTION
**Pull request by jukent**
Content is not ready to merge.

### CODE REVIEW

**Comment by jukent** [comment]
@brian-rose @ProjectPythia/education I would like to start iterating on this content with some more minds. Let me know if you are interested and we can set up some times, or feel free to make pushes to this PR.

**Comment by brian-rose** [comment]
> @brian-rose @ProjectPythia/education I would like to start iterating on this content with some more minds. Let me know if you are interested and we can set up some times, or feel free to make pushes to this PR.

I'm trying to push some changes to your branch but getting a permission error:
```
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/jukent/pythia-foundations
 ! [remote rejected] Spinup -> Spinup (permission denied)
error: failed to push some refs to 'https://github.com/jukent/pythia-foundations'
```

I've never tried to push to someone else's branch before, not sure how to proceed.

**Comment by brian-rose** [comment]
Following the discussion and instructions over in #25, I just successfully pushed to this branch. Still not sure why it worked just now when I got the permission error last night, but it works!

Here I'm just merging in the latest updates from main branch.

**Comment by brian-rose** [comment]
On formatting in the markdown files, we should prefer the code block style like
`` ``` 
a line of code ``` ``
over the inline style `` `a line of code` ``. 
I think it's easier to read (clear separation of text and code), and JupyterBook also automatically gives us a handy-dandy "copy" button for every code block.

**Comment by clyne** [comment]
@jukent, trying to review your guide as promised, but I'm having trouble with formatting. I've followed the contributor's guide precisely, but in the local rendered book I'm seeing stuff like:

Open a terminal.

.. note::

On Windows, open Anaconda Prompt. On a Mac or Linux machine, simply open Terminal.

..

Create a directory:

.. code-block:: bash

$ mkdir python_tutorial

Any ideas, anyone?

**Comment by brian-rose** [comment]
@clyne it may be that you are rendering an out-of-date version of the source? The latest version of the page you are describing is rendered here (and should look the same when you render it locally):
https://60661e6235e0e63f8268a537--pythia-foundations.netlify.app/foundations/getting-started-python/basic-python.html#reading-a-txt-file

Maybe you need to update your clone of this branch by doing
```
git pull 
```

**Comment by clyne** [comment]
I tried doing a git pull and everything is up to date. I'm wondering if there is something in my conda environment that is not being caught by environment.yml?

**Comment by dopplershift** [comment]
Is there anything weird in the terminal output when you run `jupyter-book build .`?

**Comment by brian-rose** [comment]
The reason I suggested pulling is because it looks like you are rendering content that no longer exists in the latest versions.

I suggest trying 
```
jupyter-book clean .
jupyter-book build .
```
Sometimes a clean start makes problems go away.

**Comment by clyne** [comment]
My bad. Operator error. I was on  the wrong branch. Apologies and thanks for the help.

**Comment by clyne** [comment]
@jukent , thanks for getting the ball rolling with our first actual content contribution. I’m happy to meet and iterate. Maybe a small group would be a good way to keep this moving forward. I’ve got some general comments below. Not sure that GitHub comments is the best way to iterate on this, but we’ll give it a shot. Comments below:

1. The Getting Started with Python “chapter?” is essentially a table of contents, but it doesn’t map to what is shown in the sidebar.

2. Why Python?: I might suggest including as the number one reason to use Python is that it is so widely used by the scientific community.

3. Fun with Python: The document says “Try it out in Binder…”, but there is no link or explation for Binder.

4. How to run Python: If we going to base all of our content around Jupyter notebooks, perhaps we should discuss it first (currently the terminal is discussed first)

5. Using the Conda Package…: I’d suggest maybe retitling this to something like “Managing your Python environment with Conda”, and explaining that Python is comprised of two things: the Python language which is comprised of statements, control flow, variables, etc.; and the vast Python ecosystem, which is a collection of downloadable functions that can be called from the Python language. Both of which can be most easily be managed by a package manger like Conda, which is what we will use in Project Pythia. 

6. Creating a Conda environment: The example given creates an environment named “sample_environment”. Shouldn’t we pick a name that would be more meaningful for all of our content that we can refer to over and over again? Perhaps something like “pythia-foundations-sandbox? Also, we should be consistent with hyphens vs underscores in names.

7. Running Python in Jupyter: The section “Creating a Conda environment” already shows how to create a conda environment. If we’re going to base our content on Jupyter, shouldn’t we do the conda environment creation just once? I.e. the environment creation under “Creating a Conda env.” Should provide an environment that works for all (most) of our content.

8. Python in an IDE: There is not much in here, and maybe there doesn’t need to be. The content here is all getting started information, and I think we should keep it to  a minimum so it’s not overwhelming. 

9. Quickstart: what is Python?: maybe rename to “A first Python program”. The content is not really addressing the question “what is Python”.

9a. We’re using “pythia_foundations” as the name of the scratch directory. Might this cause confusion with “pythia_foundations” the local copy of the GitHub repo? Maybe we should come up with a naming convention and hierarchy for all of the tutorial scratch spaces?
9b. Is “curl” bundled everywhere (on all platforms). I’m not sure that it is. Since we’re only using 4 lines of text from this file, perhaps we can include them with instructions to cut-n-paste to a file if curl is unavailable. 

9c. Step 8 says “open a Jupyter notebook called mysci.ipynb”, but doesn’t explain how (unless running “jupyter lab” explicity creates this notebook, which should be explained).

**Comment by brian-rose** [comment]
@jukent is there anything in this branch that we need?

I *think* all the content from here got merged along with #50. If that's true, then please close this.

**Pull request closed without merging**
