### PR TITLE
`kbd`

### PR DESCRIPTION
**Pull request by zmoon**
* use Sphinx `kbd` role in non-notebooks, HTML `<kbd>` in `.ipynb` Jupyter notebooks[^1]
* some other small changes while looking for `kbd` places
  - e.g. fixing some Markdown code blocks in `jupyterlab.ipynb`

[^1]: since the MyST markup for `kbd` wouldn't render in JupyterLab, though JupyterLab MyST support is [potentially on the way](https://twitter.com/choldgraf/status/1485666900784730112)

### CODE REVIEW

**Comment by brian-rose** [comment]
Hi @zmoon, thanks for this PR! It's a great visual upgrade. I had to manually authorize the preview workflow (I believe because you are a "first time contributor" to this repo), but it's working now and looks great.

Please click the "Ready for review" button whenever you are ready.

**Comment by zmoon** [comment]
Thanks @brian-rose. I was wondering what you guys thought of the styling of the kbd element in the built docs. I think the black background is a bit much. I like when they are light grey with a grey border, looking more like a key.

**Comment by brian-rose** [comment]
> Thanks @brian-rose. I was wondering what you guys thought of the styling of the kbd element in the built docs. I think the black background is a bit much. I like when they are light grey with a grey border, looking more like a key.

Agreed. I imagine this is something that could be tweaked in our custom Sphinx theme. @kmpaul any thoughts?

**Comment by kmpaul** [comment]
@brian-rose @zmoon:  Yeah.  It can be styled in `_static/custom.css` file, too.  That's probably where I would start.  If we decide we need to use `kbd` in other repos, we can think about making it part of the theme.

**Comment by kmpaul** [comment]
I might use something like this in a `_style/custom.css`, but I'm open to a different background color:

```css
kbd {
  color: #000;
  background-color: #DDD;
}
```

**Comment by zmoon** [comment]
@kmpaul the style I just pushed looks like this 
image
but then if you hover it looks like the key gets pushed down a bit, which is fun.

**Comment by kmpaul** [comment]
Awesome!!!!!

**Comment by brian-rose** [comment]
> @kmpaul the style I just pushed looks like this
> image
> but then if you hover it looks like the key gets pushed down a bit, which is fun.

Sounds terrific! I just clicked the approval to run preview action so we can take a look.

**Comment by brian-rose** [comment]
Ok, I took a look and I think it's fantastic. The little bit of interactivity from hovering over is nice touch.

**Comment by kmpaul** [comment]
@zmoon:  That's very cool!  I love it!

**Review by brian-rose — APPROVED** [review]
All looks great to me. Thanks very much for this contribution @zmoon

**Comment by brian-rose** [comment]
Given that this is a cosmetic change only, I'll go ahead and merge with no further review.

Thanks @zmoon, you're now officially a Pythia contributor!

**Pull request merged**
