### PR TITLE
Update Jupyter Book Preview Workflow

### PR DESCRIPTION
**Pull request by andersy005**
This PR 

(1) replaces the custom [ProjectPythia/actions/comment-netlify-preview-in-pr](https://github.com/ProjectPythia/actions/tree/main/comment-netlify-preview-in-pr) GitHub action with a combination of actively maintained actions. 

(2) Updates an existing comment (with a preview URL) instead of creating a new comment for each git push. 

Note: This PR needs to be merged for changes in the preview-book workflow https://github.com/ProjectPythia/pythia-foundations/blob/96fb41393d79da002d376aa9a8ca5d49401db6ef/.github/workflows/preview-book.yaml to take effect...

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]
Nice! Relying less on custom GitHub machinery seems to be a step in the right direction towards sustainability for our project. Also, fewer bot-generated comments and out of date links in each PR discussion should help keep us oriented.

I don't understand the GitHub Actions details well enough to give this a very thorough review, but I'm fine with merging this in order to see what it really does.

**Comment by andersy005** [comment]
Provided I did everything right when a new PR is created, the PR is updated with this comment 

test-2

Once the PR has been built, this comment is updated to 

test-1

_Ignore the fact that Preview URL in the screenshot is pointing to a commit SHA (It's what I had during the prototyping phase)_

**Comment by jukent** [comment]
I agree with @brian-rose This looks good to me, and I can see that it works on this PR, but I have much to learn about GitHub actions.

**Review by jukent — APPROVED** [review]

**Comment by andersy005** [comment]
Thank you for the review, @jukent and @brian-rose! I'm merging this and will fix any broken pieces in subsequent PRs :)

**Pull request merged**
