### PR TITLE
Use pythia-datasets in Pandas notebook

### PR DESCRIPTION
**Pull request by brian-rose**
- Update `environment.yml` to add `pythia-datasets` to our Python environment
- Update Pandas notebook to access data from `pythia_datasets`
- Remove the enso data file from this repo

### CODE REVIEW

**Comment by brian-rose** [comment]
I added some explanation within the notebook about the `DATASETS.fetch()` call. Reviewers, please offer your sage advice about whether this will help or confuse the reader.

**Review by mgrover1 — APPROVED** [review]
this looks great @brian-rose thank you for making this change!

**Comment by brian-rose** [comment]
ping @dcamron do you have a few minutes for a quick review here? I'm working on similar stuff over at #33 and it would be great to get this merged.

**Review by clyne — APPROVED** [review]
Terrific!

**Pull request merged**
