### PR TITLE
Jupyter Content

### LINKED ISSUE #97: Intro to Jupyter content
Merge or adapt material from Jupyter Meets the Earth project.

### PR DESCRIPTION
**Pull request by jukent**
This PR contains content for 2 main notebooks (getting started with Jupyter, and JupyterLab). The PR also:
- adds images and gifs for these notebooks
- updates the toc to point to the jupyterlab notebook
- updates the .md files that point to these notebooks (conda, terminal, how to run python) to follow the template

Closes #97

### CODE REVIEW

**Comment by jukent** [comment]
I seem to have a broken link somewhere. Link-checker's output is very large, making it hard to find where the broken link is.

**Comment by jukent** [comment]
Link-checker seems to be trying to open a link "hello.py" within the jupyterlab file that I never intended to be a link. When I try to change it I get a linting error.

"""
(foundations/jupyterlab: line 130016) broken    http://hellp.py - HTTPConnectionPool(host='hellp.py', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2418eb3850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
"""

**Comment by jukent** [comment]
@ProjectPythia/infrastructure I'm at a loss as to why Jupyter Book thinks "hello.py" is an external link. Any help appreciated!!

**Comment by dopplershift** [comment]
Looks like the regex finding URLs is a little aggressive. Any chance making hello a literal with backticks solves it? `` `hello.py` ``

**Comment by jukent** [comment]
> Looks like the regex finding URLs is a little aggressive. Any chance making hello a literal with backticks solves it? `` `hello.py` ``

Trying that now.

**Comment by jukent** [comment]
> Looks like the regex finding URLs is a little aggressive. Any chance making hello a literal with backticks solves it? `` `hello.py` ``

Didn't do the trick:

"""
(foundations/jupyterlab: line 130016) broken    http://hellp.py - HTTPConnectionPool(host='hellp.py', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd7bafbd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
"""

**Comment by jukent** [comment]
Okay @clyne @dcamron Sorry for all of the recent pushes. This is now ready for review

**Comment by clyne** [comment]
Great! Look forward to reviewing. Probably will have to wait until next week though :-(

**Comment by dopplershift** [comment]
Something went very wrong with the pull bot here. There are no longer any changes...

**Comment by dcamron** [comment]
> Something went very wrong with the pull bot here. There are no longer any changes...

Oh yeeps, they are very gone. Looks like the work was on @jukent main and the bot forced over it from upstream main. I think that's how it's expected to behave but uhh not ideal for this circumstance.

**Comment by dopplershift** [comment]
`git reflog` run locally might be able to find the hash for what `jukent:main` used to be and recover the changes.

**Comment by jukent** [comment]
Oops! I can fix this.

**Comment by jukent** [comment]
@dopplershift @dcamron @clyne this content is now split into two PRs #131 and #132

**Pull request closed without merging**
