### PR TITLE
Fit 01_Cartopy_Intro notebook to proposed Foundations template

### PR DESCRIPTION
**Pull request by ktyle**
I've reworked the intro to cartopy notebook so it fits the proposed foundations template that @dcamron developed on the 5/27 hackathon

### CODE REVIEW

**Comment by brian-rose** [comment]
I think to fit the template, we need to avoid using subheadings for text blocks, particularly because they clutter up the right-hand nav bar when rendered in the Jupyterbook.

I'll push an update to this branch that has a more vanilla usage of subheading markers.

**Comment by brian-rose** [comment]
@ktyle I removed a lot of subheading markers in text blocks, but also tried to add useful subheadings that will render well in the nav bar. Let me know what you think.

**Comment by brian-rose** [comment]
This should probably be revisited one more time as soon as the template is finalized and merged.

**Comment by brian-rose** [comment]
Ok team, I did some further massaging of this notebook to make it (I think) fully consistent with our new template. I also added the self-generating Cartopy logo at the top of the notebook using code from https://scitools.org.uk/cartopy/docs/latest/gallery/miscellanea/logo.html

@ktyle is this ready for a formal review? If so, please request from the Education team. (I see that you "assigned" some of us to this already, feel free to tag the same people for review or tag the team instead to use the round-robin functionality)

**Comment by ktyle** [comment]
@brian-rose looks great! Ready for review and merge.

**Comment by brian-rose** [comment]
Ok, I manually added @dcamron and @mgrover1 as reviewers since the GitHub machine chose me (I've already worked over the content) and @r-ford who isn't yet active on the project.

**Comment by brian-rose** [comment]
Side note, we should (temporarily) remove @r-ford from the team so he doesn't get tagged for reviews during tomorrow's hackathon.

**Review by mgrover1 — COMMENTED** [review]
I added a few comments/suggestions via nbviewer - the markdown file looks great. Awesome work!

**Review by mgrover1 — APPROVED** [review]
Thanks for making those changes @ktyle looks good to merge!

**Review by brian-rose — APPROVED** [review]

**Comment by ktyle** [comment]
woo-hoo!

**Pull request merged**
